import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('シードデータの投入を開始します...')

  // 既存のデータをクリア（外部キー制約を考慮した順序）
  await prisma.activityLog.deleteMany()
  await prisma.file.deleteMany()
  await prisma.folder.deleteMany()
  await prisma.payroll.deleteMany()
  await prisma.attendance.deleteMany()
  await prisma.task.deleteMany()
  await prisma.evaluation.deleteMany()
  await prisma.cardMember.deleteMany()
  await prisma.card.deleteMany()
  await prisma.boardList.deleteMany()
  await prisma.board.deleteMany()
  await prisma.workspaceMember.deleteMany()
  await prisma.workspace.deleteMany()
  await prisma.familyMember.deleteMany()
  await prisma.employee.deleteMany()

  // 社員データの作成（新しいマスターデータに基づく）
  const employees = [
    {
      employeeId: "EMP-2015-001",
      employeeNumber: "EMP-2015-001",
      employeeType: "正社員",
      name: "admin",
      email: "admin@company.com",
      phone: "090-0000-0000",
      department: "執行部",
      position: "代表取締役",
      organization: "株式会社テックイノベーション",
      team: "システム管理",
      joinDate: new Date("2015-01-01"),
      status: "active" as const,
      password: "admin",
      role: "admin" as const,
    },
    {
      employeeId: "EMP-2015-002",
      employeeNumber: "EMP-2015-002",
      employeeType: "正社員",
      name: "manager",
      email: "manager@company.com",
      phone: "090-0000-0001",
      department: "執行部",
      position: "管理者",
      organization: "株式会社テックイノベーション",
      team: "管理",
      joinDate: new Date("2015-01-01"),
      status: "active" as const,
      password: "manager",
      role: "manager" as const,
    },
    {
      employeeId: "EMP-2016-001",
      employeeNumber: "EMP-2016-001",
      employeeType: "正社員",
      name: "sub",
      email: "sub@company.com",
      phone: "090-0000-0002",
      department: "執行部",
      position: "管理者",
      organization: "株式会社テックイノベーション",
      team: "サブ管理",
      joinDate: new Date("2016-01-01"),
      status: "active" as const,
      password: "sub",
      role: "sub_manager" as const,
    },
    {
      employeeId: "EMP-2017-001",
      employeeNumber: "EMP-2017-001",
      employeeType: "正社員",
      name: "ippan",
      email: "ippan@company.com",
      phone: "090-0000-0003",
      department: "広店",
      position: "内勤",
      organization: "株式会社テックイノベーション",
      team: "営業",
      joinDate: new Date("2017-01-01"),
      status: "active" as const,
      password: "ippan",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2018-001",
      employeeNumber: "EMP-2018-001",
      employeeType: "正社員",
      name: "etsuran",
      email: "etsuran@company.com",
      phone: "090-0000-0004",
      department: "広店",
      position: "内勤",
      organization: "株式会社テックイノベーション",
      team: "営業",
      joinDate: new Date("2018-01-01"),
      status: "active" as const,
      password: "etsuran",
      role: "viewer" as const,
    },
    {
      employeeId: "EMP-2021-001",
      employeeNumber: "EMP-2021-001",
      employeeType: "正社員",
      name: "田中 太郎",
      email: "tanaka@company.com",
      phone: "090-1234-5678",
      department: "工務部",
      position: "工務",
      organization: "株式会社テックイノベーション",
      team: "バックエンドチーム",
      joinDate: new Date("2021-04-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2020-015",
      employeeNumber: "EMP-2020-015",
      employeeType: "正社員",
      name: "佐藤 花子",
      email: "sato@company.com",
      phone: "090-2345-6789",
      department: "広店",
      position: "店長",
      organization: "株式会社テックイノベーション",
      team: "エンタープライズ営業",
      joinDate: new Date("2020-07-15"),
      status: "active" as const,
      password: "pass1234",
      role: "manager" as const,
    },
    {
      employeeId: "EMP-2022-032",
      employeeNumber: "EMP-2022-032",
      employeeType: "契約社員",
      name: "鈴木 一郎",
      email: "suzuki@company.com",
      phone: "090-3456-7890",
      department: "広店",
      position: "プランナー",
      organization: "株式会社テックイノベーション",
      team: "デジタルマーケティング",
      joinDate: new Date("2022-01-10"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2019-008",
      employeeNumber: "EMP-2019-008",
      employeeType: "正社員",
      name: "高橋 美咲",
      email: "takahashi@company.com",
      phone: "090-4567-8901",
      department: "執行部",
      position: "総務",
      organization: "株式会社テックイノベーション",
      team: "人事企画",
      joinDate: new Date("2019-03-20"),
      status: "active" as const,
      password: "pass1234",
      role: "hr" as const,
    },
    {
      employeeId: "EMP-2023-045",
      employeeNumber: "EMP-2023-045",
      employeeType: "正社員",
      name: "伊藤 健太",
      email: "ito@company.com",
      phone: "090-5678-9012",
      department: "工務部",
      position: "工務",
      organization: "株式会社テックイノベーション",
      team: "フロントエンドチーム",
      joinDate: new Date("2023-04-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2024-001",
      employeeNumber: "EMP-2024-001",
      employeeType: "正社員",
      name: "山田 花子",
      email: "yamada@company.com",
      phone: "090-6789-0123",
      department: "焼山店",
      position: "店長",
      organization: "株式会社テックイノベーション",
      team: "店舗運営",
      joinDate: new Date("2024-01-01"),
      status: "active" as const,
      password: "pass1234",
      role: "store_manager" as const,
    },
    {
      employeeId: "EMP-2024-002",
      employeeNumber: "EMP-2024-002",
      employeeType: "パートタイム",
      name: "佐々木 太郎",
      email: "sasaki@company.com",
      phone: "090-7890-1234",
      department: "チカラもち",
      position: "チームリーダー",
      organization: "株式会社テックイノベーション",
      team: "サービス",
      joinDate: new Date("2024-02-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2024-003",
      employeeNumber: "EMP-2024-003",
      employeeType: "正社員",
      name: "田村 健一",
      email: "tamura@company.com",
      phone: "090-8901-2345",
      department: "福祉部",
      position: "福祉長",
      organization: "株式会社テックイノベーション",
      team: "福祉サービス",
      joinDate: new Date("2024-03-01"),
      status: "active" as const,
      password: "pass1234",
      role: "manager" as const,
    },
    {
      employeeId: "EMP-2024-004",
      employeeNumber: "EMP-2024-004",
      employeeType: "正社員",
      name: "中村 美香",
      email: "nakamura@company.com",
      phone: "090-9012-3456",
      department: "不動産部",
      position: "プランナー",
      organization: "株式会社テックイノベーション",
      team: "不動産企画",
      joinDate: new Date("2024-04-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    // 新しいマスターデータに基づく追加社員
    {
      employeeId: "EMP-2024-005",
      employeeNumber: "EMP-2024-005",
      employeeType: "派遣社員",
      name: "派遣 太郎",
      email: "haken@company.com",
      phone: "090-1111-1111",
      department: "広店",
      position: "内勤",
      organization: "株式会社テックイノベーション",
      team: "営業サポート",
      joinDate: new Date("2024-05-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2024-006",
      employeeNumber: "EMP-2024-006",
      employeeType: "業務委託",
      name: "委託 花子",
      email: "itaku@company.com",
      phone: "090-2222-2222",
      department: "工務部",
      position: "工務",
      organization: "株式会社テックイノベーション",
      team: "システム開発",
      joinDate: new Date("2024-06-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2024-007",
      employeeNumber: "EMP-2024-007",
      employeeType: "外注先",
      name: "外注 一郎",
      email: "gaichu@company.com",
      phone: "090-3333-3333",
      department: "不動産部",
      position: "プランナー",
      organization: "株式会社テックイノベーション",
      team: "企画",
      joinDate: new Date("2024-07-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2024-008",
      employeeNumber: "EMP-2024-008",
      employeeType: "正社員",
      name: "執行 次郎",
      email: "shikko@company.com",
      phone: "090-4444-4444",
      department: "執行部",
      position: "執行役員",
      organization: "株式会社テックイノベーション",
      team: "経営企画",
      joinDate: new Date("2024-08-01"),
      status: "active" as const,
      password: "pass1234",
      role: "manager" as const,
    },
    {
      employeeId: "EMP-2024-009",
      employeeNumber: "EMP-2024-009",
      employeeType: "正社員",
      name: "統括 三郎",
      email: "toukatsu@company.com",
      phone: "090-5555-5555",
      department: "広店",
      position: "統括店長",
      organization: "株式会社テックイノベーション",
      team: "店舗統括",
      joinDate: new Date("2024-09-01"),
      status: "active" as const,
      password: "pass1234",
      role: "manager" as const,
    },
    {
      employeeId: "EMP-2024-010",
      employeeNumber: "EMP-2024-010",
      employeeType: "正社員",
      name: "工務 四郎",
      email: "koumu@company.com",
      phone: "090-6666-6666",
      department: "工務部",
      position: "工務長",
      organization: "株式会社テックイノベーション",
      team: "工務管理",
      joinDate: new Date("2024-10-01"),
      status: "active" as const,
      password: "pass1234",
      role: "manager" as const,
    },
    {
      employeeId: "EMP-2024-011",
      employeeNumber: "EMP-2024-011",
      employeeType: "正社員",
      name: "アドバイザー 五郎",
      email: "advisor@company.com",
      phone: "090-7777-7777",
      department: "執行部",
      position: "アドバイザー",
      organization: "株式会社テックイノベーション",
      team: "経営アドバイス",
      joinDate: new Date("2024-11-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2024-012",
      employeeNumber: "EMP-2024-012",
      employeeType: "正社員",
      name: "広報 六郎",
      email: "kouhou@company.com",
      phone: "090-8888-8888",
      department: "執行部",
      position: "広報",
      organization: "株式会社テックイノベーション",
      team: "広報宣伝",
      joinDate: new Date("2024-12-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2024-013",
      employeeNumber: "EMP-2024-013",
      employeeType: "正社員",
      name: "経理 七郎",
      email: "keiri@company.com",
      phone: "090-9999-9999",
      department: "執行部",
      position: "経理",
      organization: "株式会社テックイノベーション",
      team: "経理管理",
      joinDate: new Date("2025-01-01"),
      status: "active" as const,
      password: "pass1234",
      role: "general" as const,
    },
    {
      employeeId: "EMP-2024-014",
      employeeNumber: "EMP-2024-014",
      employeeType: "正社員",
      name: "サービス管理 八郎",
      email: "service@company.com",
      phone: "090-0000-1111",
      department: "チカラもち",
      position: "サービス管理責任者",
      organization: "株式会社テックイノベーション",
      team: "サービス管理",
      joinDate: new Date("2025-02-01"),
      status: "active" as const,
      password: "pass1234",
      role: "manager" as const,
    }
  ]

  for (const employeeData of employees) {
    await prisma.employee.create({
      data: employeeData
    })
  }

  console.log('シードデータの投入が完了しました！')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
