export const mockEmployees = [
  {
    id: "0",
    employeeId: "EMP-2015-001",
    employeeNumber: "EMP-2015-001",
    employeeType: "employee",
    name: "admin",
    email: "admin@company.com",
    phone: "090-0000-0000",
    department: "総務・管理者",
    position: "システム管理者",
    organization: "株式会社テックイノベーション",
    team: "システム管理",
    joinDate: "2015-01-01",
    status: "active",
    password: "admin",
    role: "admin" as const,
  },
  {
    id: "0-1",
    employeeId: "EMP-2015-002",
    employeeNumber: "EMP-2015-002",
    employeeType: "employee",
    name: "manager",
    email: "manager@company.com",
    phone: "090-0000-0001",
    department: "総務・管理者",
    position: "管理者",
    organization: "株式会社テックイノベーション",
    team: "管理",
    joinDate: "2015-01-01",
    status: "active",
    password: "manager",
    role: "manager" as const,
  },
  {
    id: "0-2",
    employeeId: "EMP-2016-001",
    employeeNumber: "EMP-2016-001",
    employeeType: "employee",
    name: "sub",
    email: "sub@company.com",
    phone: "090-0000-0002",
    department: "総務・管理者",
    position: "サブ管理者",
    organization: "株式会社テックイノベーション",
    team: "サブ管理",
    joinDate: "2016-01-01",
    status: "active",
    password: "sub",
    role: "sub-manager" as const,
  },
  {
    id: "0-3",
    employeeId: "EMP-2017-001",
    employeeNumber: "EMP-2017-001",
    employeeType: "employee",
    name: "ippan",
    email: "ippan@company.com",
    phone: "090-0000-0003",
    department: "営業",
    position: "一般社員",
    organization: "株式会社テックイノベーション",
    team: "営業",
    joinDate: "2017-01-01",
    status: "active",
    password: "ippan",
    role: "general" as const,
  },
  {
    id: "0-4",
    employeeId: "EMP-2018-001",
    employeeNumber: "EMP-2018-001",
    employeeType: "employee",
    name: "etsuran",
    email: "etsuran@company.com",
    phone: "090-0000-0004",
    department: "営業",
    position: "閲覧のみ",
    organization: "株式会社テックイノベーション",
    team: "営業",
    joinDate: "2018-01-01",
    status: "active",
    password: "etsuran",
    role: "viewer" as const,
  },
  {
    id: "1",
    employeeId: "EMP-2021-001",
    employeeNumber: "EMP-2021-001",
    employeeType: "employee",
    name: "田中 太郎",
    email: "tanaka@company.com",
    phone: "090-1234-5678",
    department: "エンジニアリング",
    position: "シニアエンジニア",
    organization: "株式会社テックイノベーション",
    team: "バックエンドチーム",
    joinDate: "2021-04-01",
    status: "active",
    password: "pass1234",
    role: "general" as const,
  },
  {
    id: "2",
    employeeId: "EMP-2020-015",
    employeeNumber: "EMP-2020-015",
    employeeType: "employee",
    name: "佐藤 花子",
    email: "sato@company.com",
    phone: "090-2345-6789",
    department: "営業",
    position: "営業マネージャー",
    organization: "株式会社テックイノベーション",
    team: "エンタープライズ営業",
    joinDate: "2020-07-15",
    status: "active",
    password: "pass1234",
    role: "manager" as const,
  },
  {
    id: "3",
    employeeId: "EMP-2022-032",
    employeeNumber: "EMP-2022-032",
    employeeType: "contractor",
    name: "鈴木 一郎",
    email: "suzuki@company.com",
    phone: "090-3456-7890",
    department: "マーケティング",
    position: "マーケティングスペシャリスト",
    organization: "株式会社テックイノベーション",
    team: "デジタルマーケティング",
    joinDate: "2022-01-10",
    status: "active",
    password: "pass1234",
    role: "general" as const,
  },
  {
    id: "4",
    employeeId: "EMP-2019-008",
    employeeNumber: "EMP-2019-008",
    employeeType: "employee",
    name: "高橋 美咲",
    email: "takahashi@company.com",
    phone: "090-4567-8901",
    department: "人事",
    position: "人事部長",
    organization: "株式会社テックイノベーション",
    team: "人事企画",
    joinDate: "2019-03-20",
    status: "active",
    password: "pass1234",
    role: "hr" as const,
  },
  {
    id: "5",
    employeeId: "EMP-2023-045",
    employeeNumber: "EMP-2023-045",
    employeeType: "employee",
    name: "伊藤 健太",
    email: "ito@company.com",
    phone: "090-5678-9012",
    department: "エンジニアリング",
    position: "ジュニアエンジニア",
    organization: "株式会社テックイノベーション",
    team: "フロントエンドチーム",
    joinDate: "2023-04-01",
    status: "active",
    password: "pass1234",
    role: "general" as const,
  },
  {
    id: "6",
    employeeId: "EMP-2021-018",
    employeeNumber: "EMP-2021-018",
    employeeType: "employee",
    name: "渡辺 由美",
    email: "watanabe@company.com",
    phone: "090-6789-0123",
    department: "経理",
    position: "経理担当",
    organization: "株式会社テックイノベーション",
    team: "財務経理",
    joinDate: "2021-06-15",
    status: "leave",
    password: "pass1234",
    role: "general" as const,
  },
  {
    id: "7",
    employeeId: "EMP-2020-022",
    employeeNumber: "EMP-2020-022",
    employeeType: "contractor",
    name: "山本 大輔",
    email: "yamamoto@company.com",
    phone: "090-7890-1234",
    department: "営業",
    position: "営業担当",
    organization: "株式会社テックイノベーション",
    team: "SMB営業",
    joinDate: "2020-09-01",
    status: "active",
    password: "pass1234",
    role: "general" as const,
  },
  {
    id: "8",
    employeeId: "EMP-2018-005",
    employeeNumber: "EMP-2018-005",
    employeeType: "employee",
    name: "中村 真理子",
    email: "nakamura@company.com",
    phone: "090-8901-2345",
    department: "エンジニアリング",
    position: "テックリード",
    organization: "株式会社テックイノベーション",
    team: "アーキテクチャチーム",
    joinDate: "2018-05-10",
    status: "active",
    password: "pass1234",
    role: "manager" as const,
  },
  {
    id: "9",
    employeeId: "EMP-2022-038",
    employeeNumber: "EMP-2022-038",
    employeeType: "employee",
    name: "小林 翔太",
    email: "kobayashi@company.com",
    phone: "090-9012-3456",
    department: "マーケティング",
    position: "コンテンツマーケター",
    organization: "株式会社テックイノベーション",
    team: "コンテンツ制作",
    joinDate: "2022-08-20",
    status: "active",
    password: "pass1234",
    role: "general" as const,
  },
  {
    id: "10",
    employeeId: "EMP-2017-012",
    employeeNumber: "EMP-2017-012",
    employeeType: "employee",
    name: "加藤 恵子",
    email: "kato@company.com",
    phone: "090-0123-4567",
    department: "人事",
    position: "採用担当",
    organization: "株式会社テックイノベーション",
    team: "採用チーム",
    joinDate: "2017-11-01",
    status: "retired",
    password: "pass1234",
    role: "hr" as const,
  },
]

export const organizationData = {
  id: "ceo",
  name: "山田 太郎",
  position: "代表取締役社長",
  department: "経営",
  employeeNumber: "EMP-2015-001",
  organization: "株式会社テックイノベーション",
  team: "経営企画",
  children: [
    {
      id: "cto",
      name: "中村 真理子",
      position: "CTO",
      department: "技術部門",
      employeeNumber: "EMP-2018-005",
      organization: "株式会社テックイノベーション",
      team: "技術戦略",
      employeeCount: 45,
      children: [
        {
          id: "eng-lead",
          name: "田中 太郎",
          position: "エンジニアリング部長",
          department: "エンジニアリング",
          employeeNumber: "EMP-2021-001",
          organization: "株式会社テックイノベーション",
          team: "開発統括",
          employeeCount: 30,
        },
        {
          id: "qa-lead",
          name: "伊藤 健太",
          position: "QA部長",
          department: "品質保証",
          employeeNumber: "EMP-2023-045",
          organization: "株式会社テックイノベーション",
          team: "QA",
          employeeCount: 15,
        },
      ],
    },
    {
      id: "coo",
      name: "佐藤 花子",
      position: "COO",
      department: "事業部門",
      employeeNumber: "EMP-2020-015",
      organization: "株式会社テックイノベーション",
      team: "事業統括",
      employeeCount: 80,
      children: [
        {
          id: "sales-lead",
          name: "山本 大輔",
          position: "営業部長",
          department: "営業",
          employeeNumber: "EMP-2020-022",
          organization: "株式会社テックイノベーション",
          team: "営業統括",
          employeeCount: 35,
        },
        {
          id: "marketing-lead",
          name: "鈴木 一郎",
          position: "マーケティング部長",
          department: "マーケティング",
          employeeNumber: "EMP-2022-032",
          organization: "株式会社テックイノベーション",
          team: "マーケティング統括",
          employeeCount: 25,
        },
        {
          id: "cs-lead",
          name: "小林 翔太",
          position: "カスタマーサクセス部長",
          department: "CS",
          employeeNumber: "EMP-2022-038",
          organization: "株式会社テックイノベーション",
          team: "CS統括",
          employeeCount: 20,
        },
      ],
    },
    {
      id: "cfo",
      name: "渡辺 由美",
      position: "CFO",
      department: "管理部門",
      employeeNumber: "EMP-2021-018",
      organization: "株式会社テックイノベーション",
      team: "管理統括",
      employeeCount: 35,
      children: [
        {
          id: "hr-lead",
          name: "高橋 美咲",
          position: "人事部長",
          department: "人事",
          employeeNumber: "EMP-2019-008",
          organization: "株式会社テックイノベーション",
          team: "人事統括",
          employeeCount: 15,
        },
        {
          id: "finance-lead",
          name: "加藤 恵子",
          position: "経理部長",
          department: "経理",
          employeeNumber: "EMP-2017-012",
          organization: "株式会社テックイノベーション",
          team: "経理統括",
          employeeCount: 20,
        },
      ],
    },
  ],
}

export const kanbanTasks = [
  {
    id: "task-1",
    title: "新規採用システムの設計",
    description: "採用管理システムの要件定義とデータベース設計を行う",
    assignee: "田中 太郎",
    dueDate: "2025-01-15",
    priority: "high" as const,
    comments: 3,
    attachments: 2,
    status: "in-progress",
    labels: [
      { id: "label-1", name: "緊急", color: "#ef4444" },
      { id: "label-4", name: "機能追加", color: "#3b82f6" },
    ],
    checklists: [
      {
        id: "checklist-1",
        title: "設計タスク",
        items: [
          { id: "item-1", text: "要件定義書作成", completed: true },
          { id: "item-2", text: "ER図作成", completed: true },
          { id: "item-3", text: "API設計", completed: false },
        ],
      },
    ],
    members: [
      { id: "member-1", name: "田中 太郎" },
      { id: "member-2", name: "伊藤 健太" },
    ],
    cardColor: "",
  },
  {
    id: "task-2",
    title: "社員研修プログラムの企画",
    description: "新入社員向けの研修カリキュラムを作成する",
    assignee: "高橋 美咲",
    dueDate: "2025-01-20",
    priority: "medium" as const,
    comments: 5,
    attachments: 1,
    status: "todo",
    labels: [{ id: "label-6", name: "ドキュメント", color: "#8b5cf6" }],
    checklists: [],
    members: [{ id: "member-3", name: "高橋 美咲" }],
    cardColor: "",
  },
  {
    id: "task-3",
    title: "給与計算システムのバグ修正",
    description: "残業時間の計算ロジックに不具合があるため修正が必要",
    assignee: "伊藤 健太",
    dueDate: "2025-01-12",
    priority: "high" as const,
    comments: 8,
    attachments: 0,
    status: "review",
    labels: [
      { id: "label-1", name: "緊急", color: "#ef4444" },
      { id: "label-3", name: "バグ", color: "#dc2626" },
    ],
    checklists: [
      {
        id: "checklist-2",
        title: "修正手順",
        items: [
          { id: "item-4", text: "バグの原因特定", completed: true },
          { id: "item-5", text: "修正コード実装", completed: true },
          { id: "item-6", text: "テスト実施", completed: false },
        ],
      },
    ],
    members: [{ id: "member-4", name: "伊藤 健太" }],
    cardColor: "#fee2e2",
  },
  {
    id: "task-4",
    title: "Q4評価面談の実施",
    description: "全社員の評価面談を実施し、フィードバックを記録する",
    assignee: "佐藤 花子",
    dueDate: "2025-01-25",
    priority: "medium" as const,
    comments: 2,
    attachments: 3,
    status: "in-progress",
    labels: [{ id: "label-2", name: "重要", color: "#f59e0b" }],
    checklists: [],
    members: [
      { id: "member-5", name: "佐藤 花子" },
      { id: "member-6", name: "高橋 美咲" },
    ],
    cardColor: "",
  },
  {
    id: "task-5",
    title: "組織図の更新",
    description: "新しい部署編成に合わせて組織図を更新する",
    assignee: "山本 大輔",
    dueDate: "2025-01-10",
    priority: "low" as const,
    comments: 1,
    attachments: 1,
    status: "done",
    labels: [{ id: "label-5", name: "改善", color: "#10b981" }],
    checklists: [],
    members: [{ id: "member-7", name: "山本 大輔" }],
    cardColor: "#d1fae5",
  },
  {
    id: "task-6",
    title: "勤怠管理システムの改善提案",
    description: "現行システムの課題を洗い出し、改善案を作成する",
    assignee: "鈴木 一郎",
    dueDate: "2025-01-18",
    priority: "low" as const,
    comments: 0,
    attachments: 0,
    status: "todo",
    labels: [{ id: "label-5", name: "改善", color: "#10b981" }],
    checklists: [],
    members: [{ id: "member-8", name: "鈴木 一郎" }],
    cardColor: "",
  },
  {
    id: "task-7",
    title: "年末調整書類の確認",
    description: "全社員の年末調整書類を確認し、不備がないかチェックする",
    assignee: "渡辺 由美",
    dueDate: "2025-01-08",
    priority: "high" as const,
    comments: 4,
    attachments: 5,
    status: "review",
    labels: [
      { id: "label-1", name: "緊急", color: "#ef4444" },
      { id: "label-2", name: "重要", color: "#f59e0b" },
    ],
    checklists: [],
    members: [{ id: "member-9", name: "渡辺 由美" }],
    cardColor: "#fed7aa",
  },
  {
    id: "task-8",
    title: "社内イベントの企画",
    description: "新年会の企画と予算申請を行う",
    assignee: "小林 翔太",
    dueDate: "2025-01-22",
    priority: "medium" as const,
    comments: 6,
    attachments: 2,
    status: "todo",
    labels: [],
    checklists: [],
    members: [{ id: "member-10", name: "小林 翔太" }],
    cardColor: "",
  },
  {
    id: "task-9",
    title: "セキュリティ研修の実施",
    description: "情報セキュリティに関する全社研修を実施する",
    assignee: "中村 真理子",
    dueDate: "2025-01-30",
    priority: "medium" as const,
    comments: 2,
    attachments: 1,
    status: "in-progress",
    labels: [{ id: "label-6", name: "ドキュメント", color: "#8b5cf6" }],
    checklists: [],
    members: [{ id: "member-11", name: "中村 真理子" }],
    cardColor: "",
  },
  {
    id: "task-10",
    title: "福利厚生制度の見直し",
    description: "現行の福利厚生制度を見直し、改善案を提案する",
    assignee: "加藤 恵子",
    dueDate: "2025-01-05",
    priority: "low" as const,
    comments: 3,
    attachments: 0,
    status: "done",
    labels: [{ id: "label-5", name: "改善", color: "#10b981" }],
    checklists: [],
    members: [{ id: "member-12", name: "加藤 恵子" }],
    cardColor: "",
  },
]

export const evaluations = [
  {
    id: "eval-1",
    employeeName: "田中 太郎",
    position: "シニアエンジニア",
    department: "エンジニアリング",
    period: "2024年度 Q4",
    evaluator: "中村 真理子",
    status: "completed",
    overallScore: 4.5,
    deadline: "2025-01-15",
    scores: [
      { category: "技術力", value: 4.5 },
      { category: "業務遂行", value: 4.8 },
      { category: "コミュニケーション", value: 4.2 },
      { category: "リーダーシップ", value: 4.5 },
    ],
  },
  {
    id: "eval-2",
    employeeName: "佐藤 花子",
    position: "営業マネージャー",
    department: "営業",
    period: "2024年度 Q4",
    evaluator: "山田 太郎",
    status: "completed",
    overallScore: 4.7,
    deadline: "2025-01-15",
    scores: [
      { category: "営業成績", value: 5.0 },
      { category: "顧客対応", value: 4.8 },
      { category: "チーム管理", value: 4.5 },
      { category: "目標達成", value: 4.5 },
    ],
  },
  {
    id: "eval-3",
    employeeName: "鈴木 一郎",
    position: "マーケティングスペシャリスト",
    department: "マーケティング",
    period: "2024年度 Q4",
    evaluator: "佐藤 花子",
    status: "in-progress",
    overallScore: 0,
    deadline: "2025-01-20",
    scores: [],
  },
  {
    id: "eval-4",
    employeeName: "高橋 美咲",
    position: "人事部長",
    department: "人事",
    period: "2024年度 Q4",
    evaluator: "山田 太郎",
    status: "completed",
    overallScore: 4.3,
    deadline: "2025-01-15",
    scores: [
      { category: "採用実績", value: 4.5 },
      { category: "社員満足度", value: 4.2 },
      { category: "制度改善", value: 4.0 },
      { category: "マネジメント", value: 4.5 },
    ],
  },
  {
    id: "eval-5",
    employeeName: "伊藤 健太",
    position: "ジュニアエンジニア",
    department: "エンジニアリング",
    period: "2024年度 Q4",
    evaluator: "田中 太郎",
    status: "completed",
    overallScore: 3.8,
    deadline: "2025-01-15",
    scores: [
      { category: "技術力", value: 3.8 },
      { category: "業務遂行", value: 4.0 },
      { category: "成長意欲", value: 4.2 },
      { category: "協調性", value: 3.5 },
    ],
  },
  {
    id: "eval-6",
    employeeName: "渡辺 由美",
    position: "経理担当",
    department: "経理",
    period: "2024年度 Q4",
    evaluator: "加藤 恵子",
    status: "pending",
    overallScore: 0,
    deadline: "2025-01-25",
    scores: [],
  },
  {
    id: "eval-7",
    employeeName: "山本 大輔",
    position: "営業担当",
    department: "営業",
    period: "2024年度 Q4",
    evaluator: "佐藤 花子",
    status: "in-progress",
    overallScore: 0,
    deadline: "2025-01-18",
    scores: [],
  },
  {
    id: "eval-8",
    employeeName: "中村 真理子",
    position: "テックリード",
    department: "エンジニアリング",
    period: "2024年度 Q4",
    evaluator: "山田 太郎",
    status: "completed",
    overallScore: 4.8,
    deadline: "2025-01-15",
    scores: [
      { category: "技術力", value: 5.0 },
      { category: "リーダーシップ", value: 4.8 },
      { category: "戦略立案", value: 4.5 },
      { category: "メンタリング", value: 5.0 },
    ],
  },
]

export const payrollData = [
  {
    id: "pay-1",
    employeeId: "EMP-2021-001",
    employeeName: "田中 太郎",
    department: "エンジニアリング",
    position: "シニアエンジニア",
    period: "2025年1月",
    baseSalary: 400000,
    allowances: 50000,
    deductions: 85000,
    overtime: 45000,
    netPay: 410000,
    status: "pending",
    overtimeHours: 18,
    allowanceBreakdown: {
      commute: 15000,
      housing: 25000,
      position: 10000,
    },
    deductionBreakdown: {
      healthInsurance: 20000,
      pension: 36000,
      incomeTax: 18000,
      residentTax: 11000,
    },
  },
  {
    id: "pay-2",
    employeeId: "EMP-2020-015",
    employeeNumber: "EMP-2020-015",
    employeeType: "employee",
    name: "佐藤 花子",
    email: "sato@company.com",
    phone: "090-2345-6789",
    department: "営業",
    position: "営業マネージャー",
    organization: "株式会社テックイノベーション",
    team: "エンタープライズ営業",
    joinDate: "2020-07-15",
    status: "active",
  },
  {
    id: "pay-3",
    employeeId: "EMP-2022-032",
    employeeName: "鈴木 一郎",
    department: "マーケティング",
    position: "マーケティングスペシャリスト",
    period: "2025年1月",
    baseSalary: 380000,
    allowances: 45000,
    deductions: 78000,
    overtime: 25000,
    netPay: 372000,
    status: "paid",
    overtimeHours: 10,
    allowanceBreakdown: {
      commute: 15000,
      housing: 25000,
      position: 5000,
    },
    deductionBreakdown: {
      healthInsurance: 19000,
      pension: 34000,
      incomeTax: 16000,
      residentTax: 9000,
    },
  },
  {
    id: "pay-4",
    employeeId: "EMP-2019-008",
    employeeName: "高橋 美咲",
    department: "人事",
    position: "人事部長",
    period: "2025年1月",
    baseSalary: 500000,
    allowances: 70000,
    deductions: 110000,
    overtime: 20000,
    netPay: 480000,
    status: "paid",
    overtimeHours: 8,
    allowanceBreakdown: {
      commute: 20000,
      housing: 35000,
      position: 15000,
    },
    deductionBreakdown: {
      healthInsurance: 25000,
      pension: 45000,
      incomeTax: 25000,
      residentTax: 15000,
    },
  },
  {
    id: "pay-5",
    employeeId: "EMP-2023-045",
    employeeName: "伊藤 健太",
    department: "エンジニアリング",
    position: "ジュニアエンジニア",
    period: "2025年1月",
    baseSalary: 280000,
    allowances: 30000,
    deductions: 55000,
    overtime: 35000,
    netPay: 290000,
    status: "draft",
    overtimeHours: 14,
    allowanceBreakdown: {
      commute: 10000,
      housing: 20000,
      position: 0,
    },
    deductionBreakdown: {
      healthInsurance: 14000,
      pension: 25000,
      incomeTax: 10000,
      residentTax: 6000,
    },
  },
  {
    id: "pay-6",
    employeeId: "EMP-2021-018",
    employeeName: "渡辺 由美",
    department: "経理",
    position: "経理担当",
    period: "2025年1月",
    baseSalary: 350000,
    allowances: 40000,
    deductions: 72000,
    overtime: 15000,
    netPay: 333000,
    status: "pending",
    overtimeHours: 6,
    allowanceBreakdown: {
      commute: 15000,
      housing: 25000,
      position: 0,
    },
    deductionBreakdown: {
      healthInsurance: 17000,
      pension: 31000,
      incomeTax: 15000,
      residentTax: 9000,
    },
  },
]

export const employees = mockEmployees

export const taskTemplates = [
  {
    id: "template-1",
    title: "新機能開発タスク",
    description: "新機能の要件定義から実装、テストまでの標準的な開発フロー",
    assignee: "",
    dueDate: "",
    priority: "medium" as const,
    comments: 0,
    attachments: 0,
    status: "todo",
    labels: [{ id: "label-4", name: "機能追加", color: "#3b82f6" }],
    checklists: [
      {
        id: "checklist-template-1",
        title: "開発フロー",
        items: [
          { id: "item-t1", text: "要件定義", completed: false },
          { id: "item-t2", text: "設計書作成", completed: false },
          { id: "item-t3", text: "実装", completed: false },
          { id: "item-t4", text: "単体テスト", completed: false },
          { id: "item-t5", text: "結合テスト", completed: false },
          { id: "item-t6", text: "レビュー", completed: false },
        ],
      },
    ],
    members: [],
    cardColor: "",
  },
  {
    id: "template-2",
    title: "バグ修正タスク",
    description: "バグの調査から修正、テストまでの標準的な修正フロー",
    assignee: "",
    dueDate: "",
    priority: "high" as const,
    comments: 0,
    attachments: 0,
    status: "todo",
    labels: [
      { id: "label-1", name: "緊急", color: "#ef4444" },
      { id: "label-3", name: "バグ", color: "#dc2626" },
    ],
    checklists: [
      {
        id: "checklist-template-2",
        title: "修正手順",
        items: [
          { id: "item-t7", text: "バグの再現確認", completed: false },
          { id: "item-t8", text: "原因調査", completed: false },
          { id: "item-t9", text: "修正実装", completed: false },
          { id: "item-t10", text: "テスト実施", completed: false },
          { id: "item-t11", text: "動作確認", completed: false },
        ],
      },
    ],
    members: [],
    cardColor: "#fee2e2",
  },
  {
    id: "template-3",
    title: "ドキュメント作成タスク",
    description: "技術文書やマニュアルの作成標準フロー",
    assignee: "",
    dueDate: "",
    priority: "low" as const,
    comments: 0,
    attachments: 0,
    status: "todo",
    labels: [{ id: "label-6", name: "ドキュメント", color: "#8b5cf6" }],
    checklists: [
      {
        id: "checklist-template-3",
        title: "作成手順",
        items: [
          { id: "item-t12", text: "目次作成", completed: false },
          { id: "item-t13", text: "下書き作成", completed: false },
          { id: "item-t14", text: "レビュー依頼", completed: false },
          { id: "item-t15", text: "修正反映", completed: false },
          { id: "item-t16", text: "最終確認", completed: false },
        ],
      },
    ],
    members: [],
    cardColor: "#e9d5ff",
  },
  {
    id: "template-4",
    title: "システム改善タスク",
    description: "既存システムの改善提案から実装までのフロー",
    assignee: "",
    dueDate: "",
    priority: "medium" as const,
    comments: 0,
    attachments: 0,
    status: "todo",
    labels: [{ id: "label-5", name: "改善", color: "#10b981" }],
    checklists: [
      {
        id: "checklist-template-4",
        title: "改善フロー",
        items: [
          { id: "item-t17", text: "現状分析", completed: false },
          { id: "item-t18", text: "改善案作成", completed: false },
          { id: "item-t19", text: "承認取得", completed: false },
          { id: "item-t20", text: "実装", completed: false },
          { id: "item-t21", text: "効果測定", completed: false },
        ],
      },
    ],
    members: [],
    cardColor: "#d1fae5",
  },
  {
    id: "template-5",
    title: "定例ミーティング準備",
    description: "定例会議の準備から実施、議事録作成までのフロー",
    assignee: "",
    dueDate: "",
    priority: "low" as const,
    comments: 0,
    attachments: 0,
    status: "todo",
    labels: [],
    checklists: [
      {
        id: "checklist-template-5",
        title: "準備手順",
        items: [
          { id: "item-t22", text: "アジェンダ作成", completed: false },
          { id: "item-t23", text: "資料準備", completed: false },
          { id: "item-t24", text: "参加者への通知", completed: false },
          { id: "item-t25", text: "会議実施", completed: false },
          { id: "item-t26", text: "議事録作成", completed: false },
          { id: "item-t27", text: "議事録共有", completed: false },
        ],
      },
    ],
    members: [],
    cardColor: "",
  },
]
